# Site settings
title: Gabriel Halpern
description: Gabriel Halpern
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://halpern.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriel Halpern
user_description: Hey! My name is Gabriel Halpern and I am a Software Developer. I recently graduated from Elon University with a Bachelor of Science in Computer Science and a minor in Data Science. 
user_title: Software Developer
email: gabriel@halpern.dev
linkedin_username: gabriel-halpern
github_username: ghalpern25

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
