# Site settings
title: Gabriel Halpern
description: Gabriel Halpern
baseurl: "halpern.dev" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriel Halpern
user_description: //TODO Description of myself
user_title: Software Developer
email: ghalpern@newview.org
linkedin_username: gabriel-halpern
github_username: ghalpern25

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
